<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.css">
    <link rel="stylesheet" href="/assets/css/style.css">

    <title>Hello, SendPulse!</title>
  </head>
  <body class="p-top-25">
    <div class="container">
      <div class="row justify-content-md-center">
        <div class="col col-lg-4">
          <form id="sp-form-parser" id="sp-form-parser" action="/parser" method="post">
            <div class="form-group">
              <label for="exampleInputEmail1">Parser by url</label>
              <input name="url-parser" id="sp-input-url" pattern="https://.*" size="30" type="url" placeholder="https://example.com" class="form-control" value="https://www.xml-sitemaps.com/">
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Parser by url</label>
              <input name="url-parser" id="sp-input-nesting" pattern="\d*" min="1" max="99" value="1" type="number" class="form-control">
            </div>
            <button class="btn btn-primary">Parse</button> <a href="/result">Result page</a>
          </form>
          
        </div>
      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"  crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.js" crossorigin="anonymous"></script>
    <script src="/assets/js/app.js"></script>
    <script>
     
      $(document).ready(() => {
        (new appParserEmail).init({
          selectors: {
            formp_parser  : '#sp-form-parser',
            input_url     : '#sp-input-url', 
            input_nesting : '#sp-input-nesting' 
          }
        });

      })
    </script>
  </body>
</html>