<script src="//code.jquery.com/jquery-3.1.0.slim.min.js"></script>
<script src="/assets/libs/json-browse/json-browse/jquery.json-browse.js"></script>
<link href="/assets/libs/json-browse/json-browse/jquery.json-browse.css"rel="stylesheet">

<table class="table">
    <thead>
        <tr>
            <th scope="col">Ссылка</th>
            <th scope="col">Глубина</th>
            <th scope="col">Состояние</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($taskList as $task): ?>
            <tr>
                <td><?= $task['url'] ?></td>
                <td>
                    <pre id="json-<?= $task['_id'] ?>" class="json-body"></pre>
                    <script>$('#json-<?= $task['_id'] ?>').jsonBrowse(<?= json_encode(json_decode($task['result']) , JSON_PRETTY_PRINT) ?>); </script>
                </td>
                <td><?= $task['url'] ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>



